
# redis 配置
redis:
  host: 127.0.0.1
  port: 6379
  password: redis!@@&

mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: test

#storage:
#  database:
#    driver: mysql
#    source: root:root@tcp(127.0.0.1:3306)/test
#  redis:
#    addr: 127.0.0.1:6379
#    read_timeout: 0.2s
#    write_timeout: 0.2s